### ISSUE TITLE
Preprocessing.py

### ISSUE THREAD

**Issue by TrentBrick** [OpenProtein/openprotein#17]
I downloaded CASP12 from ProteinNet and put the datafiles in `data/raw` I then added these lines to the bottom of `preprocessing.py`: 

`use_gpu=False
process_raw_data(use_gpu, force_pre_processing_overwrite=True)`

Running it gave me a read file error: `FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/raw\\sample.txt'`

So I changed this line (line 25 in the `process_raw_data` function: `filename = file_path.split('/')[-1]`

to this: `filename = file_path.split('\\')[-1]` and it then worked.

**Comment by TrentBrick** [comment]
I have added a pull request for this change here #18 

Disclaimer: I have never contributed to opensource projects before or ever made a pull request!

**Comment by JeppeHallgren** [comment]
Hey @TrentBrick ,

Thanks for filing this. As I wrote on the PR, I believe \\ is Windows specific. Should be quite simple to check was OS the code is running under though: https://stackoverflow.com/questions/1854/python-what-os-am-i-running-on :)

**Comment by TrentBrick** [comment]
Yes I am currently running Windows, should have realized this may be Windows specific!

**Comment by JeppeHallgren** [comment]
Fixed in https://github.com/OpenProtein/openprotein/pull/18
